SET @HOUR := -1;
SELECT @HOUR := @HOUR + 1 as HOUR, IFNULL((
    SELECT COUNT(*)
    FROM ANIMAL_OUTS
    WHERE @HOUR = DATE_FORMAT(DATETIME, "%H")
    GROUP BY DATE_FORMAT(DATETIME, "%H")
    ORDER BY DATE_FORMAT(DATETIME, "%H")
),0) as COUNT
FROM ANIMAL_OUTS a
WHERE @HOUR < 23
